version: "3"
networks:
  hvnam-network:
    external: true
services:
    hvnam-cukcuk:
        image: hvnam-cukcuk
        container_name: hvnam-cukcuk
        restart: always
        networks:
            - hvnam-network
        ports:
            - '1612:80'
        build:
            context: .
            dockerfile: MISA.CukCuk.Api/Dockerfile

  